### ISSUE TITLE
Erweiterung schafft Fehler bei Veranstaltungen (You must not have more than one auto_item parameter)

### ISSUE THREAD

**Issue by FlorinvV** [iMi-digital/imi_mm_changelanguage#11]
Hallo,

ich musste gerade feststellen, dass die Erweiterung sich wohl mit den Contao-Events beißt...
Die Meta-Models funktionieren bei mir super, wenn ich allerdings im FE auf die Detailseite eines gewöhnlichen Contao-Events gehe, wirft es mir diesen Fehler aus:

`[2020-11-25 15:58:58] request.INFO: Matched route "contao_frontend". {"route":"contao_frontend","route_parameters":{"_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\FrontendController::indexAction","_scope":"frontend","_locale":"de","alias":"aktuell/veranstaltungen-und-messen/detail/eventTitel/","_route":"contao_frontend"},"request_uri":"https://www.meineSeite.de/de/aktuell/veranstaltungen-und-messen/detail/eventTitel/","method":"GET"} []`

`[2020-11-25 15:58:58] security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} []`

`[2020-11-25 15:58:58] app.CRITICAL: An exception occurred. {"exception":"[object] (RuntimeException(code: 0): You must not have more than one auto_item parameter at /www/htdocs/w01767ee/meineSeite/vendor/terminal42/contao-changelanguage/library/Terminal42/ChangeLanguage/Navigation/UrlParameterBag.php:188)"} []
`

Ist dieses Problem schon irgendwie bekannt? Bzw. habe ich irgendwo vielleicht eine Einstellung übersehen?

Vielen Dank schonmal!
Beste Grüße
Florin

**Comment by amenk** [comment]
Hi Florin,

das Problem ist mir noch nicht bekannt, eine Einstellung dazu gibt es auch nicht.

Wir haben die Extension wohl bisher auf keiner Seite die auch Events nutzt im Einsatz.

Welche Contao Version verwendest du genau?
Ist das mit dem Demo Template nachstellbar?

Kannst du das ggf. Debuggen und einen Pull Request machen? Wir würden uns freuen :-D

Grüße,

Alex

**Comment by FlorinvV** [comment]
Hi Alex,

der Fehler tritt auf bei der Contao-Version 4.4.54
Ob es mit dem Demo-Template nachstellbar ist weiß ich leider nicht, dass
müsste man testen....

Ich bin leider programmiertechnisch nicht sehr affin, deshalb wäre ich beim
debuggen leider nicht sehr hilfreich...

Wenn ihr noch irgendwelche Infos bräuchtet, versuche ich was ich kann um
euch die zu liefern.

Beste Grüße,
Florin

Am Mi., 25. Nov. 2020 um 16:22 Uhr schrieb Alexander Menk <
notifications@github.com>:

**Comment by amenk** [comment]
Danke für die Info.

Wenn es dringend ist, können wir bezahlten Support anbieten, ansonsten würden wir abwarten bis Zeit ist, oder bis das Problem in einem unserer Projekte auftritt.

**Comment by lennier83** [comment]
Wer das gleiche Problem hat mit Events und MetaModels und ChangeLanguage in einer Installation ("You must not have more than one auto_item parameter"):
Ein Hack-Fix sind zwei Anpassungen:
1) MM -> Filtereinstellungen in z.B. "FE Link Detail" = URL-Parameter -> LEER LASSEN (kein auto_item)
2) ImiMMChangeLanguageObserver.php -> $alias = \Input::get('LEER LASSEN'); (kein auto_item)

Dadurch wird der auto_item-alias zwar nicht mehr ausgelassen (und somit ein etwas länger alias wie "de/details/mm_alias/produkt.html) generiert), aber funktioniert so mit der Übersetzung und Events macht keine Probleme.

Das ist nicht perfekt, aber am einfachsten ist eh beim Sprachswitch auf die Liste zu leiten, nicht auf Details :-)

**Comment by amenk** [comment]
Vielen Dank.

Mich würde interessieren wie man das Problem genau nachstellt, zum Beispiel auf einer Standardinstallation.

Werden auf der Event Seite auch Metamodels genutzt oder einfach nur das Modul und Metamodels installiert?

**Comment by lennier83** [comment]
Hallo amenk

Events (inkl. "https://github.com/kmielke/calendar-extended-bundle" bei mir) und Metamodels sind installiert aber nicht auf der gleichen Seite (also es gibt eine normale Eventseite und eine für Metamodels die, bei mir, auch nicht verbunden sind. Sprachswitch ist Global eingebaut).
Sobald man deine recht gute Extension installiert, geht der Event-Detail-Sprachswitch nicht mehr.
=> request.CRITICAL: Uncaught PHP Exception RuntimeException: "You must not have more than one auto_item parameter" at /html/muenchtest/vendor/terminal42/contao-changelanguage/library/Terminal42/ChangeLanguage/Navigation/UrlParameterBag.php line 188 {"exception":"[object] (RuntimeException(code: 0): You must not have more than one auto_item parameter at /html/muenchtest/vendor/terminal42/contao-changelanguage/library/Terminal42/ChangeLanguage/Navigation/UrlParameterBag.php:188)"} []

Falls dir das auf den Nagel brennt wieso das ist, ich habe da eine Dummyinstallation der betreffenden Seite bei der man machen kann was man will :-)
In meinem Falls ist das jetzt nicht wichtig, wollte nur sagen das ich das Problem auch habe und noch nicht drauf gekommen bin warum...deswegen dieser unschöne Hack falls es für jemandem gerade wichtig ist :-)

**Comment by amenk** [comment]
Falls du Lust hast dann später auch ein bisschen zu testen, könntest du mir tatsächlich die dummy installation zusenden (SSH, Admin) und ich würde demnächst mal gucken ob ich das fixen kann. "A Punkt menk at imi Punkt de" ist meine Adresse.. @lennier83

**Comment by lennier83** [comment]
Ich mache dir mal alles fertig und sende was. Mercie :-)

**Comment by amenk** [comment]
Letztendlich greift die Extension auf jeder Seite mit einem auto_item

Ihr könntet versuchen vor diese Zeile

https://github.com/iMi-digital/imi_mm_changelanguage/blob/4daee4f60604b80f7dc213d515ae35975781d444/contao/classes/ImiMMChangeLanguageObserver.php#L166

ein

      if (!empty($currentMetaModels))

Zu setzen.

Ich denke dann tritt der Fehler nicht mehr auf.

Freue mich über Feedback.

**Comment by lennier83** [comment]
Mh. Scheint nicht zu gehen.
Zu 
 if (!empty($currentMetaModels)) {
        $event->getUrlParameterBag()->setUrlAttribute('items', $alias);
}
geändert und Cache neu.

**Comment by amenk** [comment]
Welche contao, MM, und Modulversion verwendest du? @lennier83

**Comment by amenk** [comment]
Ich kann das Problem hier zwischenzeitlich mit Contao 4.9 .16, MM2.2 (Early Access), imi_mm_changelanguage 3.0.0 nachstellen

**Comment by amenk** [comment]
@lennier83 
Interessanterweise hat der Fix aus https://github.com/iMi-digital/imi_mm_changelanguage/issues/11#issuecomment-869061233 bei mir funktioniert. Aber ich habe auch noch keine MetaModels erstellt (konnte den Fehler bereits ohne Tatsächliche Meta-Models reproduzieren)

Ich habe aber noch einen anderen Ansatz, der sicherer sein sollte.
Versuche bitte mal diesen Branch:

https://github.com/iMi-digital/imi_mm_changelanguage/pull/12

Falls du noch eine ältere Version mit MM2.1 verwendest, sollte es auch möglich sein, die beiden Changes in der alten version zu machen. Wichtig ist auch der Eintrag in der autoload.ini - danach Cache neu aufbauen.

**Comment by amenk** [comment]
Hier wäre auch noch ein branch für die 2er Version - der ist allerdings völlig ungetestet.

https://github.com/iMi-digital/imi_mm_changelanguage/tree/dev2.x/fix%2F11-crash-on-event-page

Vielleicht kann @FlorinvV diesen testen, dann würde ich den als v2.0.2 taggen

**Comment by lennier83** [comment]
Nice on :-D
Funktioniert jetzt alles in meinem dummy.
Contao 4.9.16, MM 2.1, imi_mm_changelanguage 3.0, und der Fix unter https://github.com/iMi-digital/imi_mm_changelanguage/tree/fix/11-crash-on-events-page

Events switchen super, MM kann mit auto_item betrieben werden, und die Sprach-Switches machen soweit was sie soll überall :-)

**Comment by amenk** [comment]
Gefixt in 2.0.2 und 3.0.1

**Comment by amenk** [comment]
Danke fürs testen @lennier83
