### ISSUE TITLE
errors by updating MetaModels 2.3 in contao with php 8.1

### ISSUE THREAD

**Issue by Svetlana-Pribylova** [iMi-digital/imi_mm_changelanguage#14]
Warning: Attempt to read property "metamodel_layout" on null 
![errors_updating_with_php_8 1](https://user-images.githubusercontent.com/82762180/218112484-e86169f7-adf1-46b9-b0d7-f35878c3c592.png)

**Comment by cscheibelhut** [comment]
this seems to be a solution for that problem:
`if (isset($objModule->metamodel_layout))` in line 56 in ImiMMChangeLanguageObserver.php

**Comment by amenk** [comment]
@cscheibelhut possible, I hope that does not break anything, but try it please.

**Comment by amenk** [comment]
fixed in https://github.com/iMi-digital/imi_mm_changelanguage/pull/15
