### ISSUE TITLE
Beispielkonfiguration

### ISSUE THREAD

**Issue by JLNNN** [iMi-digital/imi_mm_changelanguage#3]
Hi,
ich habe eine Seite
www.example.tld/de/hotel/mein-super-hotel/
und erhalte dort leider nach der Installation dieser Erweiterung (v1.2.2) über Composer, Metamodels (v2.0.0-alpha14) und terminal42/contao-changelanguage (v3.1.3) noch keinen Link
www.example.tld/en/hotel/my-super-hotel/
obwohl die Seiten an sich existieren/funktionieren. 
Stattdessen lande ich auf der "ohne Parameter"-Seite www.example.tld/en/hotel/.
Könnt ihr mir vielleicht einen Tipp geben, was ich falsch mache?
LG!

**Comment by amenk** [comment]
Wie sind die metamodels im backend konfiguriert und wie in die Seite eingebunden?

**Comment by JLNNN** [comment]
Uff :D Also eigentlich "wie immer", d. h. ich habe meine Modelle angelegt, kann Datensätze in Input-Felder eingeben und diese erfolgreich speichern. Im Frontend erhalte ich dann eine Liste, habe mit einem auto_item Filter einen Link auf eine Detailseite und erhalte dort ebenfalls die gewünschten Details. Soweit also alles lauffähig. Lediglich der Switch zu einer anderen Sprache funktioniert nicht, da verliert er immer die Referenz.

**Comment by amenk** [comment]
Was ich meine ist -  wie die Frontend Module eingebunden sind. Also Content Elemente oder irgendwas mit insert_tags vielleicht? Es gibt im Code Logik, die die Metamodels welche auf der Seite benutzt werden automatisch ermittelnt und darüber die Suche der übersetzten URL anstößt. Kann es daran liegen? Dann kann man das Metamodel welches MM_ChangeLanguage verweden soll auch manuell konfigurieren (siehe README)

**Comment by JLNNN** [comment]
Nein, die Module sind ganz normal als Inhaltselement vom Typ MetaModel-Liste eingebunden. Auf der Detail-Seite mit dem Filter " Einfache Abfrage für Attribut alias (URL-Parameter: auto_item)".

**Comment by amenk** [comment]
Kannst du mal mit Xdebug durch die Extension gehen und gucken was da so passiert? Bzw. wo er aussteigt.

**Comment by JLNNN** [comment]
Ich muss gestehen mit Xdebug habe ich bisher noch gar nicht gearbeitet. Ich hoste zwar bei Uberspace, müsste das Modul dort aber erst installieren, etc. Gibt es auch eine einfachere Möglichkeit, das zu debuggen? Eine Fehlermeldung erhalte ich ja in dem Sinne nicht, es steht auch nichts in den Logs. Es scheint mir, als würde er schlichtweg den Parameter einfach nicht erkennen.

So oder so - danke dir bis hierhin für deine Mühe!

**Comment by amenk** [comment]
puh ... am besten mal lokal aufsetzen.
Man kann natürlich an allen möglichen Stellen mit die und vardump "debuggen".

**Comment by amenk** [comment]
Hast du das zum laufen bekommen? Evtl. auch nochmal eine aktuelle Version des Modules & MetaModels probieren .. ansonsten würde ich das Issue hier mal schließen ...

**Comment by JLNNN** [comment]
@amenk Entschuldige das späte Feedback - nein, ich habe es nicht mehr probiert, da mein Kunde mit der Lösung, stattdessen auf die Startseite gelinkt zu werden, auch zufrieden war.
