### ISSUE TITLE
Kein "URL-Parameter beibehalten" im Modul Sprachwechsler

### ISSUE THREAD

**Issue by pointout** [iMi-digital/imi_mm_changelanguage#4]
Hallo,

ich habe heute ein Update von MM und changelanguage und imi_mm_changelanguage
gemacht.

contao 3.5.27
imi/imi_mm_changelanguage 	1.2.2
terminal42/contao-changelanguage 	dev-hotfix/3.1.4 (587b58dc)
metamodels/core 	dev-master (08b50223)

Nun fehlt die Checkbox "URL-Parameter beibehalten" im Modul Sprachwechsler und ich erhalte die Fehlermeldung: 
`Fatal error: Call to undefined method MetaModels\Factory::getDefaultFactory() in [...]/system/modules/imi_mm_changelanguage/classes/ImiMMChangeLanguageObserver.php on line 46`

und die Seite lädt nicht. Wenn ich imi/imi_mm_changelanguage deinstalliere, funktioniert der Sprachwechsel, aber ohne Parameterübergabe.

**Comment by amenk** [comment]
Bitte den terminal42/contao-changelanguage dev-hotfix/3.1.4 rausnehmen und die offizielle neuste Version von contao-changelanguage verwenden

**Comment by pointout** [comment]
Welches Paket ist das genau?
Ich habe terminal42/contao-changelanguage dev-hotfix/3.1.4 entfernt. 
Über die Suche in der Paketverwaltung finde ich sonst nur contao-legacy/changelanguage 3.1.3.9005. Das verweist auf  terminal42/contao-changelanguage und gibt die selbe Fehlermeldung aus.
terminal42/contao-changelanguage 3.1.3 funktioniert nicht, damit lässt sich kein Changelanguage-Modul einrichten.

**Comment by amenk** [comment]
habe mich vertan. Wir hatten früher mal einen eigenen hotfix Fork von contao-changelanguage.

Mit der hier haben wir getestet:
https://packagist.org/packages/terminal42/contao-changelanguage#3.1.3

**Comment by pointout** [comment]
mit der Version habe ich es auch probiert, aber da bekomme ich bei den Modulen keinen "Sprachwechsler" zur Auswahl.
![changelanguage313-packete](https://cloud.githubusercontent.com/assets/8960545/26487522/21a56ed6-4200-11e7-87aa-64424dc51a2b.PNG)

![changelanguage](https://cloud.githubusercontent.com/assets/8960545/26487504/16056658-4200-11e7-97d6-8f4840f55741.PNG)

Mit dem Hotfix kann ich den Sprachwechsler auswählen, bekomme aber die Fehlermeldung im Frontend und es fehlt die Checkbox "URL-Parameter beibehalten":

![changelanguage314hotfix-packete](https://cloud.githubusercontent.com/assets/8960545/26487583/5ea75cc2-4200-11e7-8737-f97e0682bdfc.PNG)

![changelanguage314hotfix](https://cloud.githubusercontent.com/assets/8960545/26487585/60703e3e-4200-11e7-8810-970666bfa26a.PNG)

**Comment by pointout** [comment]
Die Fehlermedlung im Frontend bekomme ich übrigens auch mit terminal42/contao-changelanguage 3.1.3.

**Comment by pointout** [comment]
Mit deinstalliertem imi/imi_mm_changelanguage 	1.2.2 funktioniert terminal42/contao-changelanguage 3.1.3.

**Comment by Webstylerin** [comment]
Bekomme die selbe Fehlermeldung wenn ich imi_mm_changelanguage installiert habe:

`Fatal error: Uncaught exception Error with message Call to undefined method MetaModels\Factory::getDefaultFactory() thrown in system/modules/imi_mm_changelanguage/classes/ImiMMChangeLanguageObserver.php on line 46
`

Die Option für die URL-Parameter habe ich auch nicht. Entweder, die Parameter sollen gänzlich weg gelassen werden oder eben MM-entsprechend übersetzt werden.

Hat jemand zwischenzeitlich eine Lösung gefunden?

imi/imi_mm_changelanguage 1.2.2
terminal42/contao-changelanguage 3.1.6
metamodels/bundle_all 2.0.0

**Comment by amenk** [comment]
@Webstylerin Bitte re-testen --- das sollte jetzt gefixt sein, war eine Inkompatbilität mit der aktuellen MetaModels Version

**Comment by Webstylerin** [comment]
@amenk Habe Contao auf 3.5.33 hochgezogen und ein Composer Update durchgeführt. Leider exakt das selbe Problem. Sobald ich [imi_mm_changelanguage] aktiviere, kommt die oben genannte Fehlermeldung.

imi/imi_mm_changelanguage 1.2.2 (selbe Version, richtig so?)
terminal42/contao-changelanguage 3.1.7
metamodels/bundle_all 2.0.0

**Comment by amenk** [comment]
@Webstylerin Die aktuelle Version ist 1.3.0
https://github.com/iMi-digital/imi_mm_changelanguage/releases

**Comment by Webstylerin** [comment]
@amenk Ich bekomm die Version 1.3.0 über den Composer nicht geladen. Wo hakts?

`The requested package imi/imi_mm_changelanguage =1.3.0 exists as imi/imi_mm_changelanguage[1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.2.1, 1.2.2, dev-master] but these are rejected by your constraint.`

**Comment by amenk** [comment]
wie sieht deine composer.json aus? Ist da vielleicht sowas wie 1.2.* ?

**Comment by amenk** [comment]
Bitte nochmal versuchen, packagist.org war nicht up-to-date

**Comment by Webstylerin** [comment]
Danke, hat geklappt, Version ist nun 1.3.1. Der Fehler ist nun auch weg! :)

Noch klappt das mit dem Übersetzen der Filter nicht, kann aber gut sein, dass das zugrunde liegende MetaModel nicht richtig eingestellt ist. Da muss ich noch mal ran.
