### ISSUE TITLE
\MetaModels\Factory::byTableName ist in MM 2.0 entfernt

### ISSUE THREAD

**Issue by zonky2** [iMi-digital/imi_mm_changelanguage#5]
wurde als deprecated warning ausgegeben und ist inzwischen entfernt

https://github.com/iMi-digital/imi_mm_changelanguage/blob/master/contao/classes/ImiMMChangeLanguageObserver.php#L126

http://metamodels.readthedocs.io/de/latest/reference/interfaces/metamodels.html#factory-interface

**Comment by amenk** [comment]
@zonky2 danke! :-)
